### ISSUE TITLE
Work On Rv1106

### ISSUE THREAD

**Issue by wallEVA96** [FengD/object_detection_tracking_rk3588#2]
Can It work on RV1106？？？It has tested？

**Comment by FengD** [comment]
> Can It work on RV1106？？？It has tested？

I did not test on RV1106 EVB. But I checked the code. The yolov8 adaption part is release by official. So the inference part should be work, as detect 2d is not a though task. Btw, What I confirmed is that the obb is not working well on rk3588.

**Comment by FengD** [comment]
> Can It work on RV1106？？？It has tested？

RV1106 has 0.5Tops AI capacity. We have tried running yolov3 on s32v234 NXP, four years ago 13fps by not using the fpn part, which has only 0.08Tops. So I think 0.5Tops is enough to run a 2d detect network. if you have a RV1106 EVB tried to execute the example first in the rknn model zoo.
